# Site settings
title: Books @ Stockflare
email: info@stockflare.com
description: "Books @ Stockflare is a great list of the best books in finance and investing. It's what we recommend to anyone novice or professional."
baseurl: ""
url: "http://books.stockflare.com"

# Build settings
markdown: kramdown
permalink: pretty
